ci: Parallelize E2E testing with GHA Matrix strategy. (#2565)
This commit refactors our Github Actions Workflow for Pull Requests to
generate a matrix of jobs for our E2E testing, one per test package.
This allows running our E2E tests across multiple GHA runners, reducing
the pain of any one E2E test failing.

Signed-off-by: Philip Conrad <philip@chariot-chaser.net>

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -157,11 +157,63 @@ jobs:
         env:
           GOPRIVATE: github.com/styrainc/
 
-  test-e2e:
-    name: Test E2E
+  test-e2e-prep-matrix:
+    name: Test E2E Setup
+    runs-on: ubuntu-24.04
+    needs: prereqs
+    outputs:
+      matrix: ${{ steps.set-matrix.outputs.matrix }}
+    steps:
+      - name: Check out code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0
+      - name: Generate the job matrix from test packages in the e2e folder
+        id: set-matrix
+        working-directory: e2e
+        run: ../build/github-actions/gen-go-test-job-matrix.sh
+        env:
+          TAGS: use_opa_fork,e2e
+      - name: Generate GitHub App Token
+        id: generate_token
+        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
+        with:
+          app_id: ${{ secrets.PLATFORM_AUTOMATION_GH_APP_ID }}
+          private_key: ${{ secrets.PLATFORM_AUTOMATION_GH_APP_PEM_KEY }}
+      - name: Override GH Token Env Var
+        run: echo "GH_API_TOKEN=${{ steps.generate_token.outputs.token }}" >> $GITHUB_ENV
+      - uses: open-policy-agent/setup-opa@34a30e8a924d1b03ce2cf7abe97250bbb1f332b5 # v2.2.0
+      - name: Check out code
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
+        with:
+          fetch-depth: 0
+      - uses: jdx/mise-action@7a111ead46986ccad89a74ad013ba2a7c08c9e67 # v2.2.1
+        env:
+          GITHUB_TOKEN: ${{ env.GH_API_TOKEN }}
+      - name: Setup github api token
+        run: git config --global url.https://git:$GH_API_TOKEN@github.com/.insteadOf https://github.com/
+      - name: Run go mod tidy
+        working-directory: e2e
+        run: go mod tidy
+      - name: display go.sum diff
+        working-directory: e2e
+        run: |
+          git diff --exit-code go.sum && exit 0
+          echo "# go.sum diff" >> $GITHUB_STEP_SUMMARY
+          echo '```diff' >> $GITHUB_STEP_SUMMARY
+          git diff go.sum >> $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+  test-e2e-run-matrix:
+    name: Test E2E - ${{ matrix.package }}
     runs-on: ubuntu-24.04
     needs:
+      - test-e2e-prep-matrix
       - goreleaser
+    strategy:
+      fail-fast: false
+      matrix:
+        package: ${{ fromJson(needs.test-e2e-prep-matrix.outputs.matrix) }}
     steps:
       - name: Tune GitHub-hosted runner network
         uses: smorimoto/tune-github-hosted-runner-network@bb252dcb5c8609a31087e7993daa086f5a1c0069 # v1.0.0
@@ -207,22 +259,54 @@ jobs:
       - name: Prep e2e prisma tests
         run: npm ci
         working-directory: e2e/prisma
-      - run: make e2e
+      - name: Get EOPA version for e2e tests
+        id: eopa-version
+        run: |
+          EOPA_VERSION=$(git describe --abbrev=0 --tags | sed s/^v//)
+          echo "version=$EOPA_VERSION" >> $GITHUB_OUTPUT
+      #- run: make e2e
+      - name: Run go test for package
+        run: |
+          # Create a temporary file for stderr, then tee stderr to that file.
+          STDERR_FILE=$(mktemp)
+          go mod tidy
+
+          # Temporarily disable error propagation
+          set +e
+
+          go test -p 1 --tags=use_opa_fork,e2e github.com/styrainc/enterprise-opa-private/e2e/${{ matrix.package }} -v -count=1 2> >(tee "$STDERR_FILE" >&2)
+          TEST_EXIT_CODE=$?
+
+          # # Re-enable error propagation
+          set -e
+
+          # Check if stderr has the build constraints error message:
+          if grep -q "build constraints exclude all Go files in" "$STDERR_FILE"; then
+            # Cancel the workflow
+            echo "::warning::Cancelling workflow because build constraints exclude all Go files. This will still report as a green Success marker"
+            echo ":warning: Job cancelled: No Go files to test due to build constraints" >> $GITHUB_STEP_SUMMARY
+            exit 0
+          else
+            # Return the original exit code from go test
+            exit $TEST_EXIT_CODE
+          fi
+        working-directory: e2e
         env:
           BINARY: ${{ steps.enterprise-opa.outputs.binary }}
+          EOPA_VERSION: ${{ steps.eopa-version.outputs.version }}
           EOPA_LICENSE_TOKEN: ${{ secrets.STYRA_LOAD_LICENSE_TOKEN }}
           # credentials for data.git plugin
           GIT_GITHUB_TOKEN: ${{ secrets.E2E_GIT_GITHUB_TOKEN }}
           GIT_AZURE_TOKEN: ${{ secrets.E2E_GIT_AZURE_TOKEN }}
           GIT_GITLAB_TOKEN: ${{ secrets.E2E_GIT_GITLAB_TOKEN }}
-      - name: display go.sum diff
-        run: |
-          git diff --exit-code go.sum && exit 0
-          echo "# go.sum diff" >> $GITHUB_STEP_SUMMARY
-          echo '```diff' >> $GITHUB_STEP_SUMMARY
-          git diff go.sum >> $GITHUB_STEP_SUMMARY
-          echo '```' >> $GITHUB_STEP_SUMMARY
-        working-directory: e2e
+
+  test-e2e-success:
+    name: Test E2E
+    runs-on: ubuntu-22.04
+    needs:
+      - test-e2e-run-matrix
+    steps:
+      - run: echo "All E2E tests succeeded, or were skipped for a non-fatal reason."
 
   proto-docs-push:
     name: Push Protobuf docs to BSR
